version: '3'

services:
  backend:
    container_name: 'backend'
    build:
      context: .
      dockerfile: ./configs/backend/backend.Dockerfile
    environment:
      - MONGO_HOST=$MONGO_HOST
      - MONGO_USER=$MONGO_USER
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_USE_SRV=$MONGO_USE_SRV
      - SECRET_KEY=$SECRET_KEY
      - ALGORITHM=$ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES
      - API_KEY=$API_KEY
      - USE_RANDOM=$USE_RANDOM
    restart: on-failure
    ports:
      - 8000:8000

  frontend:
    container_name: 'frontend'
    build:
      context: .
      dockerfile: ./configs/frontend/frontend.Dockerfile
    environment:
      - REACT_APP_API_URL=$REACT_APP_API_URL
    restart: on-failure
    ports:
      - 3000:3000
